version: '3.8'

services:
  nodeapp:
    build: .
    container_name: node-express-app
    restart: always
    ports:
      - "3000:3000" # Node.js application on port 3000
    environment:
      - MONGO_URL=${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - mern_network

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    networks:
      - mern_network

volumes:
  mongo-data:

networks:
  mern_network:
    driver: bridge
